name: CD pipeline

on:
 workflow_run:
    workflows: ["CI Pipeline"]
    types:
        - completed

jobs:

  build:

    runs-on: [self-hosted,linux]

    steps:
    - name: Pull Docker Image
      run: sudo docker pull vijeshvn/fastapi:latest
    - name: list docker
      run: sudo docker ps -all      
    - name: delete old container
      run: sudo docker rm -f fastapi-container || true
    - name: run docker
      run: sudo docker run -d -p 8080:8080 --name fastapi-container vijeshvn/fastapi
    - name: list docker
      run: sudo docker ps -all
    - name: kernal
      run: uname -a