name: CD pipeline

on:
 workflow_run:
    workflows: ["CI Pipeline"]
    types:
        - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Pull Docker Image
      run: sudo docker pull vijeshvn/fastapi:latest
    - name: delete old container
      run: docker rm -f fastapi-container || true
    - name: run docker
      run: sudo docker run -d -p 8080:8080 --name fastapi-container vijeshvn/fastapi